import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'


export const metadata = {
  title: 'Unsplash Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
